### ISSUE TITLE
[SettingView] UI 컴포넌트 그리기

### ISSUE THREAD

**Issue by PJunyeong** [DeveloperAcademy-POSTECH/MC3-Team16-Mony#37]
- [x] 네비게이션 바

- [x] 텍스트 필드 오토 레이아웃

- [x] 커스텀 달력 바

- [x] 디바이더

**Comment by Guel-git** [comment]
@PJunyeong 2주치 캘린더를 불러오는 부분을 제외하고 다른 부분 구현 완료했습니다. 제가 코드 읽어보고 직접 연결해보려고 했는데.. 도저히 모르겠네요.. 일단 내일 5시 전까지 최대한 해보고 도저히 안되면 부탁드려도 될까요..?

**Comment by Guel-git** [comment]
@PJunyeong 노아.. 전에 작성해주셨던 issue랑 이것저것 찾아보면서 2주짜리 캘린더 그리기를 계속 시도해봤는데요.. 계속 에러가 뜨거나 안 나오는 문제가 발생해서요,,, 혹시 시간 되신다면 2주치 캘린더 부분 추가해주실 수 있으실까요? 다른 자잘자잘한 버그 해결이랑, LaunchScreen과 로고 넣는 거는 제가 담당해서 진행하겠습니다.. 부탁드립니다..ㅠㅠㅠㅠ
