### ISSUE TITLE
Lottie Package 다운로드

### ISSUE THREAD

**Issue by Guel-git** [DeveloperAcademy-POSTECH/MC3-Team16-Mony#50]
CheckOrderView에서 OrderResultView로 navigation 되는 과정에서 사용될 Lottie Animation 을 사용하기 위한 Package를 다운 받는 프로세스입니다.

XCode > Add Package 
우측 상단에 https://github.com/airbnb/lottie-ios.git 붙혀넣기
lottie-ios package 다운 (Up to Major Version 으로 옵션 변경)

**Comment by PJunyeong** [comment]
달력 뷰에도 활용했습니다..!!

**Comment by Guel-git** [comment]
develop에서 풀 받아서 확인했습니다! 피그마 Hifi final 반영하신 거 맞죠?

**Comment by PJunyeong** [comment]
로티.. 말씀하시는 건가요?? 일단 주문 뷰 -> 영수증 뷰 로티를 그대로 재활용했습니다
