### ISSUE TITLE
[CheckOrderView] Lottie Animation 추가

### ISSUE THREAD

**Issue by Guel-git** [DeveloperAcademy-POSTECH/MC3-Team16-Mony#51]
- [x] Lottie package file 다운
- [x] Lottie JSON file 추가
- [x] Lottie 연결
- [x] 사이즈 위치 조정
- [x] Animation 두 번 반복
- [x] navigation delay 추가

**Comment by PJunyeong** [comment]
와우 달력 뷰에서도 로티 추가하고 싶어요!
