### ISSUE TITLE
[ConfrimStatusView_G] 1000의 배수 가격대에서는 totalPrice 값이 잘 찍히지 않습니다

### ISSUE THREAD

**Issue by PJunyeong** [DeveloperAcademy-POSTECH/MC3-Team16-Mony#61]
![Simulator Screen Shot - iPhone 13 - 2022-07-28 at 16 41 58](https://user-images.githubusercontent.com/95460398/181451023-261663cf-11ba-411a-aa5b-0e7782e25e6f.png)

데이터 바인딩이 끝난 뒤 총 가격이 4000원, 3000원 등 천의 배수로 끝나는 가격을 영수증으로 넘길 때 표시되는 가격에 이상이 있습니다. 계산 과정에서 나오는 이슈인 것 같아 문의 드립니다. 고쳐주세요!!

**Comment by Guel-git** [comment]
내용 확인했습니다. 로직을 잘못 짜서 수정해서 위 이슈에 등록하고 새로운 pr 만들겠습니다! 감사합니다 :)

**Comment by Guel-git** [comment]
버그 해결한 후 pr 날렸습니다~ 확인 부탁드립니다 :)
