### ISSUE TITLE
자잘자잘한 버그/이슈 해결_G

### ISSUE THREAD

**Issue by PJunyeong** [DeveloperAcademy-POSTECH/MC3-Team16-Mony#69]
#### 제가 그렸던 화면들에서 나온 자잘자잘한 버그/이슈들 해결하기 위한 issue 입니다.
아래 나온 뷰들은 거의 저만 수정할 것 같아서 한 브랜치에서 작업해서 pr 날리겠습니다.

[CheckOrderView]
- [x] 로티 배경색이랑 opacity 값 바꾸기
- [x] 회색 글씨 바꾸기
- [x] 주문 한 번만 들어가도록 handling
- [x] 1000 단위 가격이 잘못 표시되는 버그 해결하기

[OrderResultView]
- [x] Button 위치 이상함 > 수정 필요
- [x] 회색 글씨 바꾸기

[ConfirmStatusView]
- [x] 회색 글씨 바꾸기 (베리 확인 필요_내일)

---------------------------------------------------------------
현재 주문 완료 버튼이 되었을 때 로티 화면 -> 주문 영수증 페이지가 나오는 데요, 이때 주문 완료 버튼을 여러 번 클릭 시 -> 주문이 여러 개 생성되고 있는 것 같습니다.

버튼 최초 선택 이후에는 선택이 되지 않도록 isUserInteractionEnabled를 False로 설정해주실 수 있을까요?

**Comment by PJunyeong** [comment]
혹은 다른 방법으로 주문 한 번 이후에는 그 시점의 동일한 주문을 막아버리고 싶어요!

**Comment by Guel-git** [comment]
내용 확인했습니다! 내일 중으로 조건 추가해서 공유드릴게요!
